export const dataRealisation = [
  {
    id: 1,
    name: 'Booki',
    category: 'HTML',
    image: require('./assets/images/P2.webp'),
    link: 'https://chahinez125.github.io/BOOKI/',
    description: 'Un site de réservation pour des séjours.',
    problematic: 'Développer un site en respectant strictement les spécifications fonctionnelles et techniques',
    Realisation: "intégrer l'interface du site en utilisant uniquement du HTML et du CSS, selon les maquettes fournies par l'UI designer",
    githubLink: 'https://github.com/Chahinez125/BOOKI', // Add GitHub link
     
  },
  {
    id: 2,
    name: 'Sophie Bluel',
    category: 'JavaScript , HTML , CSS',
    link: 'https://github.com/Chahinez125/pp33dev',
    description: 'Page web dynamique',
    problematic: 'Aucune',
    Realisation: "Manipulation des éléments du DOM et gestion des évenments utilisateurs.",
    githubLink: 'https://github.com/Chahinez125/pp33dev', 
    image: require('./assets/images/P3.webp'),
  },
  {
    id: 3,
    name: 'Nina Carducci',
    category: 'Lighthous',
    image: require('./assets/images/P4.webp'),
    link: 'https://chahinez125.github.io/p4-Nina/',
    description: 'Débug et optimisation d un site.',
    problematic: 'Aucune.',
    Realisation: "Optimisation des performances d'un site web et debug d'un site web",
    githubLink: 'https://github.com/Chahinez125/p4-Nina', 
     
  },
  {
    id: 4,
    name: 'Kasa',
    category: 'React , scss',
    link: 'https://github.com/Chahinez125/projet5_kasa',
    description: 'Application web de location immobilier.',
    problematic: 'Aucune.',
    Realisation:"Inisialisation d'une application avec React App, configuration de la navigation entre les pages avec React-Router et développement d'une interface web avec Sass",
    githubLink: 'https://github.com/Chahinez125/projet5_kasa', 
    image: require('./assets/images/P5.webp'),
  },
  {
    id: 5,
    name: 'Mon vieux Grimoire',
    category: 'NodeJs , Express , Mongodb , Crud',
    link: 'https://github.com/Chahinez125/Mon_Vieux_Grimoire',
    description: "Développement du backend d'un site. ",
    problematic: "Aucun problématique rencontré dans la réalisation de ce projet.",
    Realisation: "Stocker des données de façon sécurisée et mise en oeuvre des opération CRUD de maniére sécurisée",
    githubLink: 'https://github.com/Chahinez125/Mon_Vieux_Grimoire', 
    image: require('./assets/images/P6.webp'),
  },
];
