export const dataRealisation = [
  {
    id: 1,
    name: 'Booki',
    category: 'HTML',
    image: require('./assets/images/P2.webp'),
    link: 'https://chahinez125.github.io/BOOKI/',
    description: 'Un site de réservation pour des séjours.',
    problematic: 'Développer un site en respectant strictement les spécifications fonctionnelles et techniques',
    Realisation: "intégrer l'interface du site en utilisant uniquement du HTML et du CSS, selon les maquettes fournies par l'UI designer",
    githubLink: 'https://github.com/Chahinez125/BOOKI', 
     
  },
  {
    id: 2,
    name: 'Sophie Bluel',
    category: 'JavaScript , HTML , CSS',
    link: 'https://github.com/Chahinez125/pp33dev',
    description: 'Page web dynamique',
    problematic: ' développer plusieurs nouvelles fonctionnalités tout en intégrant le design fourni.',
    Realisation: "La solution était de suivre le tableau Kanban pour coder les pages et les modales demandées.",
    githubLink: 'https://github.com/Chahinez125/pp33dev', 
    image: require('./assets/images/P3.webp'),
  },
  {
    id: 3,
    name: 'Nina Carducci',
    category: 'Lighthous',
    image: require('./assets/images/P4.webp'),
    link: 'https://chahinez125.github.io/p4-Nina/',
    description: 'Débug et optimisation d un site.',
    problematic: "Optimiser performances et SEO du site de Nina Carducci, corriger bugs de navigation et filtres dans la galerie.",
    Realisation: "Optimisation des images, SEO, accessibilité, référencement local (Schema.org), metas réseaux sociaux, correction de bugs, et rapport détaillé des impacts.",
    githubLink: 'https://github.com/Chahinez125/p4-Nina', 
     
  },
  {
    id: 4,
    name: 'Kasa',
    category: 'React , scss',
    link: 'https://github.com/Chahinez125/projet5_kasa',
    description: 'Application web de location immobilier.',
    problematic: "Respecter les contraintes de React et React Router, découper en composants modulaires, éviter les erreurs, sans librairies externes ",
    Realisation:"Structuration avec composants réutilisables, gestion dynamique des routes avec React Router, et style avec Sass.",
    githubLink: 'https://github.com/Chahinez125/projet5_kasa', 
    image: require('./assets/images/P5.webp'),
  },
  {
    id: 5,
    name: 'Mon vieux Grimoire',
    category: 'NodeJs , Express , Mongodb , Crud',
    link: 'https://github.com/Chahinez125/Mon_Vieux_Grimoire',
    description: "Développement du backend d'un site. ",
    problematic: "Développer une API pour un site de notation de livres, en collaboration avec un développeur front-end, avec optimisation des images et Green Code.",
    Realisation: "Back-end adapté avec API pour référencement et notation, intégrant optimisation des images pour performances optimales.",
    githubLink: 'https://github.com/Chahinez125/Mon_Vieux_Grimoire', 
    image: require('./assets/images/P6.webp'),
  },
];
